In [2]:
# READING USERS DF

import pandas as pd
import numpy as np
import os
os.chdir("c://Users//gufer//OneDrive//Documentos//FIAP//Fase_05//ML_Engineer_Datathon/")

In [3]:
def get_evaluation_data() -> pd.DataFrame:
    """Pega os dados de avaliação.

    Returns:
        pd.DataFrame: DataFrame com os dados de avaliação (features + target)
    """
    # Caminhos dos arquivos de avaliação
    X_test_path = "data/train/X_test.parquet"
    y_test_path = "data/train/y_test.parquet"

    # Carregar os DataFrames
    X_test = pd.read_parquet(X_test_path)
    y_test = pd.read_parquet(y_test_path)
    
    # Adiciona a coluna TARGET ao DataFrame de features
    X_test["TARGET"] = y_test
    
    # Renomeia DataFrame de features
    eval_df = X_test

    return eval_df

In [4]:
get_evaluation_data()

,isWeekend,issuedDatetime,relLocalState,relLocalRegion,relThemeMain,relThemeSub,userTypeFreq,dayPeriodFreq,localStateFreq,localRegionFreq,themeMainFreq,themeSubFreq,TARGET
0,False,2022-07-01 18:01:14,0.702703,0.702703,0.054054,0.054054,0.867253,0.205542,0.420428,0.420428,0.675038,0.753636,5.564775
1,False,2022-07-12 17:30:56,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636,25.220086
2,False,2022-02-05 14:49:21,0.721519,0.721519,NaN,NaN,0.867253,0.544154,0.125476,0.125476,0.000000,0.000000,-0.041459
3,False,2022-07-14 19:25:42,0.944444,0.402778,NaN,NaN,0.867253,0.216425,0.165553,0.016222,0.000000,0.000000,1.070360
4,False,2022-07-01 18:01:14,0.702703,0.702703,0.054054,0.054054,0.867253,0.205542,0.420428,0.420428,0.675038,0.753636,5.564775
...,...,...,...,...,...,...,...,...,...,...,...,...,...
667222,False,2022-06-24 14:10:46,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636,8.125553
667223,False,2022-07-15 13:34:24,0.702703,0.702703,NaN,NaN,0.867253,0.216425,0.420428,0.420428,0.000000,0.000000,10.362192
667224,False,2022-07-26 09:00:47,0.363636,0.272727,NaN,NaN,0.132747,0.544154,0.165553,0.041513,0.000000,0.000000,0.844657
667225,False,2022-07-12 17:30:56,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636,25.220086
667226,False,2022-06-24 14:10:46,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636,8.125553

In [5]:
from typing import Tuple
from config import logger

def load_train_data() -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Carrega os dados de treino a partir de arquivos Parquet.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]: DataFrames contendo X_train e y_train.
    """
    base_train_path = os.path.join("data", "train")
    X_train_path = os.path.join(base_train_path, "X_train.parquet")
    y_train_path = os.path.join(base_train_path, "y_train.parquet")
    
    logger.info(f"Carregando X_train de {X_train_path}...")
    X_train = pd.read_parquet(X_train_path)
    
    logger.info(f"Carregando y_train de {y_train_path}...")
    y_train = pd.read_parquet(y_train_path)
    
    return X_train, y_train

2025-02-27 10:39:41,311 - INFO - Ambiente: dev

In [6]:
X_train, y_train = load_train_data()

2025-02-27 10:39:41,335 - INFO - Carregando X_train de data\train\X_train.parquet...
2025-02-27 10:39:41,417 - INFO - Carregando y_train de data\train\y_train.parquet...

In [8]:
y_train

            TARGET
0        25.220086
1         5.110230
2         0.962531
3         5.564775
4         3.244410
...            ...
1556855   0.227597
1556856  25.220086
1556857   2.785324
1556858  -0.230356
1556859   1.693590

[1556860 rows x 1 columns]

In [7]:
X_train.drop(columns="issuedDatetime")

,isWeekend,relLocalState,relLocalRegion,relThemeMain,relThemeSub,userTypeFreq,dayPeriodFreq,localStateFreq,localRegionFreq,themeMainFreq,themeSubFreq
0,False,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636
1,False,0.828571,0.219048,NaN,NaN,0.132747,0.216425,0.165553,0.023307,NaN,NaN
2,True,0.789474,0.105263,NaN,NaN,0.867253,0.205542,0.165553,0.010908,NaN,NaN
3,False,0.702703,0.702703,0.054054,0.054054,0.867253,0.205542,0.420428,0.420428,0.675038,0.753636
4,False,0.736264,0.153846,NaN,NaN,0.867253,0.544154,0.072026,0.004754,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1556855,True,1.000000,0.097222,NaN,NaN,0.867253,0.216425,0.165553,0.006382,NaN,NaN
1556856,False,0.702703,0.702703,0.054054,0.054054,0.867253,0.544154,0.420428,0.420428,0.675038,0.753636
1556857,False,0.597826,0.597826,NaN,NaN,0.867253,0.216425,0.047594,0.047594,NaN,NaN
1556858,True,1.000000,1.000000,0.333333,0.333333,0.132747,0.205542,0.009543,0.007367,0.197864,0.183901
1556859,False,0.187500,0.083333,NaN,NaN,0.867253,0.205542,0.165553,0.041513,NaN,NaN